config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users
  get "/" => "home#index"
  get "signin" => "sessions#new", as: :new_sessions
  post "signin" => "sessions#create", as: :sessions
  delete "signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :due_date, presence: true
  validates :todo_text, length: { minimum: 2 }
  belongs_to :user

  def self.overdue
    all.where("due_date < ? and (not completed)", Date.today)
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.completed
    where(completed: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if (current_user_id)
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if (user && user.authenticate(params[:password]))
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid. Please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      :todo_text => todo_text,
      :due_date => due_date,
      :completed => false,
      :user_id => current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">Welcome to the Todo Home Page</h1>
<h3 class="Home-authenticate">
   If you are a new user, <%= link_to "sign up here", new_user_path %>
</h3>
<h3 class="Home-authenticate">
   If you are an existing user, <%= link_to "sign-in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class = "UserHeader">
        Welcome <%= @current_user.first_name %>
        <%= link_to "sign-out", destroy_session_path, method: "delete",class: "sign_out_link" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class = "Flash-error">
          <%= flash[:error] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSection-title">
    <p class="TodoSectionTitle_text"><%= section_head %></p>
    <% completed_count = todos.completed.count%>
    <p class="TodoSectionTitle_remainingCount"><%= (render_completed) ? "#{completed_count} /#{todos.count}" :  "0 /#{(todos.count - completed_count)}" %></p>
  </div>

  <ul>
    <% todos.all.each do |todo| %>
        <li class="TodoItem">
            <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
                <%= check_box_tag 'completed',
                  value = "finished",
                  checked = todo.completed ? true : false,
                  class: 'TodoItem_checkbox',
                  onclick:"this.form.submit()"
                  %>
            <% end %>

            <p class = <%= (todo.completed) ? "TodoItem_completed" : "TodoItem_Text" %>> <%= todo.todo_text %> </p>

            <% if(show_due_date) %>
              <p class="TodoItem_date"><%= todo.due_date.to_s(:short) %></p>
            <% end %>

            <a href="javascript:void(0)" class="TodoItem_delete">
              <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                <%= image_submit_tag("trashcan.png",class:"TodoItem-deleteImg") %>
              <% end %>
            </a>

        </li>
    <%end%>
  </ul>

</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
      <h1 class="TodoPage-title">My Todo-List</h1>

      <%= form_with(url: "/todos", method: "post" , class: "AddTodo") do %>
        <%= text_field_tag 'todo_text', nil, placeholder: "what's next ?",autofocus: true, class: 'AddTodo-text' %>
        <%= date_field_tag 'due_date', nil, class: 'AddTodo-date' %>
        <%= submit_tag "Add", class: "AddTodo-button" %>
      <% end %>
      <%= render partial: "todo-section", locals: {
          section_head: "Overdue",
          todos: @todos.overdue,
          show_due_date: true,
          render_completed: false,
       } %>
       <%= render partial: "todo-section", locals: {
          section_head: "Due Today",
          todos: @todos.due_today,
          show_due_date: false,
          render_completed: true,
      } %>
       <%= render partial: "todo-section", locals: {
          section_head: "Due Later",
          todos: @todos.due_later,
          show_due_date: true,
          render_completed: true,
      } %>
</main>

app/views/users/new.html.erb
<p class = "NewUsers-title">Welcome New User!</p>

<section class = "Usersnew">
  <%= form_with(url: users_path) do |form| %>
    <div class = "Form-section">
      <p class = "FormInput-label">First name: </p>
      <%= form.text_field :first_name, class:"Form-input" %>
    </div>

    <div class = "Form-section">
      <p class = "FormInput-label">Last name: </p>
      <%= form.text_field :last_name, class:"Form-input"  %>
    </div>

    <div class = "Form-section">
      <p class = "FormInput-label">Email: </p>
      <%= form.email_field :email, class:"Form-input"  %>
    </div>

    <div class = "Form-section">
      <p class = "FormInput-label">Password: </p>
      <%= form.password_field :password, class:"Form-input"  %>
    </div>

    <div class = "Form-section">
     <%= form.submit "Sign-up", class:"Form-submit"  %>
    </div>

  <% end %>
</section>